FROM node:15 as build
WORKDIR /build
ENV PATH /build/node_modules/.bin:$PATH
COPY package.json .
COPY package-lock.json .
COPY .npmrc .
RUN npm install
COPY . .
RUN npm run build
RUN ls -al
# production environment
FROM node:15
WORKDIR /app
COPY --from=build /build/dist /app/dist
COPY --from=build /build/.env /app
COPY --from=build /build/exec.sh /app
ENV PORT 9000
EXPOSE 9000
RUN ls -al /app
RUN ls -al /app/dist
#CMD ["node", "dist/index.js"]
CMD ["bash", "exec.sh"]

